
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'closecurlybraces closeparantheses condition do next opencurlybraces openparantheses semicolon statements updatingexpression whileassignment : do next stmstm : opencurlybraces next statements semicolon next updatingexpression semicolon next closecurlybraces while exprexpr : openparantheses condition closeparantheses semicolon'
    
_lr_action_items = {'do':([0,],[2,]),'$end':([1,4,15,19,],[0,-1,-2,-3,]),'next':([2,5,8,11,],[3,6,9,12,]),'opencurlybraces':([3,],[5,]),'statements':([6,],[7,]),'semicolon':([7,10,18,],[8,11,19,]),'updatingexpression':([9,],[10,]),'closecurlybraces':([12,],[13,]),'while':([13,],[14,]),'openparantheses':([14,],[16,]),'condition':([16,],[17,]),'closeparantheses':([17,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),'stm':([3,],[4,]),'expr':([14,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assignment","S'",1,None,None,None),
  ('assignment -> do next stm','assignment',3,'p_do','DoWhile.py',20),
  ('stm -> opencurlybraces next statements semicolon next updatingexpression semicolon next closecurlybraces while expr','stm',11,'p_stm','DoWhile.py',27),
  ('expr -> openparantheses condition closeparantheses semicolon','expr',4,'p_expr','DoWhile.py',30),
]
